# Where things are
destination         : ./_site
permalink: /:title:output_ext

# Markdown
markdown: kramdown
kramdown:
  auto_ids: true

# Front Matter
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
     nothing:
 

