# Gem ~ Github Pages set webpage in safe mode, so plugins can't be used.'
# plugins:
# - jemoji

# Where things are
destination         : ./_site
permalink: /:title:output_ext


collections:
    findings:
        output: true
    indexes:
        output: true

# Markdown
markdown: kramdown
encoding: UTF-8
kramdown:
  auto_ids: true

# Front Matter
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
     nothing:
 

