# Gem ~ Github Pages set webpage in safe mode, so plugins can't be used.'
# plugins:
# - jemoji

# Where things are
destination         : ./_site
permalink: /:title


collections:
    findings:
        output: true
        permalink: /:collection/:title
    indexes:
        output: true
        permalink: /:collection/:title
    indexes-extras:
        output: true
        permalink: /indexes/:title
        sort_by: date


# Markdown
markdown: kramdown
encoding: UTF-8
kramdown:
  auto_ids: true

# Front Matter
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
     permalink: /:title
 

